travis:
  secure:
    BINSTAR_TOKEN: EdgbrNe1QqrOBdWJcS3+5N6Vs6BHUMn/VynrZIydIHZuOl2qHud4tPWztYWw4LPOAV09i8bck6y30sX8U7fbk9dclD3Yoc2zqt71QuEEK3T3e3mCH4dwDCWe63dqOeqsFuQ9Ed/sRrVvTrMBp3TUWrk9HN9WXfWFJaquyWafiCVsAwlvyt6iVuT3PA/M1hO14GZxLadA6F6ws6CYXz2es1fXHknMWm6jznjMv+9+XRpXG0EMmBuvqommhcjfYYAeBDkc2XYKTNE8ruM7NOJMFJG6m82uEdgAOd7X3z9UjcQD02Ii0xF8HVFGaLlaoAyyRVItCatv21ticT+QrE2m4KPmbjI/zQBmEcxRC1PlPNqSl3Dq/qW8SjtuGE8ozms5A713TvPvwnZwmtxXHYaQg3Sl5aAwCBYQiQc8SPFFzxXHTDUjbRHDpSAWI/65NL66rMwuy2VPKvJHjS1E6I+oQ64hmGOk1ClsfGhhgDXsYZgOvM6alkxAvgkw3ptnZaFNA9RZn3JQVnr7A1m7pBrMkzzBOQdIJovAQ9sJAn2GSioGjORKt5t3De1bvCEmXC3Ex1LT7Y+SHNUwcJoFD9CpFIHH+YtETI700h71ZU44ZC2yhp5hhvHQR0urwuDa6zX5ADazo+SlhTZyUXJytVfATEdsKNEEHp7q/9EOObjcp7A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
